### PR TITLE
Move minutes of meeting into subdirectory

### PR DESCRIPTION
**Pull request by magnusbaeck**
### Applicable Issues
N/A; directly reflects TC decision

### Description of the Change
Since MEETINGS.md has grown rather large the TC decided on 2021-05-20 to restructure that document. We hereby introduce a "meetings" subdirectory where we add modified copies of the original MEETINGS.md; one for all BTC meetings and one for the TC meetings for 2021.

### Alternate Designs
* A deeper hierarchy like docs/meetings was considered but was deemed unnecessary.
* Changing MEETINGS.md to a symlink to meetings/README.md was considered but rejected since it displays poorly on github.com and might work in less than great ways on Windows.

### Benefits
MEETINGS.md won't grow indefinitely.

### Possible Drawbacks
Existing deep links like https://github.com/eiffel-community/community/blob/master/MEETINGS.md#May-20-2021 will break.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com\>

### CODE REVIEW

**Comment by magnusbaeck** [comment]
Deploying this PR will take some care given the HackMD configuration. The existing HackMD document must be reconfigured to point to the new file in the repository.

Should we attempt to preserve the link in the BTC archive document, i.e. create a new HackMD document containing the BTC meetings and link it to MEETINGS_BTC.md or is that unnecessary since it's an archived document? In the latter case I'll remove the HackMD links in MEETINGS_BTC.md.

**Review by t-persson — APPROVED** [review]

**Review by m-linner-ericsson — APPROVED** [review]
LGTM but you change the HackMD settings before pushing else it will overwrite.

**Comment by magnusbaeck** [comment]
> LGTM but you change the HackMD settings before pushing else it will overwrite.

Yes, as noted in an earlier comment some care will be required upon submission. I also need to rebase this PR since the 2021-06-03 TC meeting minutes have been pushed from HackMD.

**Review by e-backmark-ericsson — APPROVED** [review]

**Comment by magnusbaeck** [comment]
HackMD document resynced and a push of the June 17 minutes produced the nice and clean commit 38374a39b811e796d62414541ee3e73fbd1163d7.

**Pull request merged**
