### PR TITLE
Add Eiffel Events .NET SDK to PROJECTS and CONTACT

### PR DESCRIPTION
**Pull request by erkist**
### Applicable Issues
Fixes https://github.com/eiffel-community/community/issues/121

### Description of the Change
Add Eiffel Events .NET SDK to PROJECTS and CONTACT as per PROJECT_LIFECYCLE

### Alternate Designs
N/A

### Benefits
Project and contact information available to others.

### Possible Drawbacks
N/A

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Erik Sternerson, erik.sternerson@dowhile.se

### CODE REVIEW

**Comment by erkist** [comment]
Note: The repo has not been created yet, this PR should not be merged until the repo exists.

**Review by magnusbaeck — APPROVED** [review]

**Review by t-persson — APPROVED** [review]

**Review by m-linner-ericsson — APPROVED** [review]

**Review by e-backmark-ericsson — APPROVED** [review]

**Comment by magnusbaeck** [comment]
I was just about to merge this PR but I noticed that eiffelevents-sdk-dotnet-maintainers@googlegroups.com doesn't appear to have been created. Was this overlooked @erkist? 

Also, please add a CODEOWNERS file to your repo (see #7).

**Comment by erkist** [comment]
> I was just about to merge this PR but I noticed that [eiffelevents-sdk-dotnet-maintainers@googlegroups.com](mailto:eiffelevents-sdk-dotnet-maintainers@googlegroups.com) doesn't appear to have been created. Was this overlooked @erkist?

I think I have created it? Maybe there is some setting I have missed? It was a few years since I last created a google group...

image


> 
> Also, please add a CODEOWNERS file to your repo (see #7).

Will do!

**Comment by magnusbaeck** [comment]
> I think I have created it? Maybe there is some setting I have missed? It was a few years since I last created a google group...

Ah, you probably have the "Who can see the group" setting set to "Group members" (which probably is the default). I don't think that's a problem.

**Pull request merged**
