### PR TITLE
Add Drawio library for Eiffel symbols

### PR DESCRIPTION
**Pull request by Fredrik10a**
### Applicable Issues
N/A

### Description of the Change
This PR will add a DrawIO library .xml file containing fundamental Eiffel symbols for modeling with Eiffel in the free tool called DrawIO.

### Alternate Designs
N/A

### Possible Drawbacks
This is the first version and has been aligned with the Eiffel coloring, though slightly brighter to comply with the coloring present in DrawIO.

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Fredrik Ellis fredrik.ellis@enewit.se

### CODE REVIEW

**Comment by Fredrik10a** [comment]
This version does only contain the symbols, I am thinking of adding prepared LINKs with TYPES defined in the next Version.
If this is seem as a good idea?

**Review by m-linner-ericsson — DISMISSED** [review]
Thanks for the contribution! 

Was debating with myself if it was better in the eiffel (protocol) repo but we don't have any good place there either so this looks fine.

If you want to, please feel free to add a description in https://github.com/eiffel-community/community/tree/master/howtos

**Comment by Fredrik10a** [comment]
I will fix the HowTo

**Comment by magnusbaeck** [comment]
I'm getting a "this.ui.hashValue is not a function" error message when attempting to load https://raw.githubusercontent.com/eiffel-community/community/8689a0faeb9024580b84fadcb1fd310e88e1b045/resources/drawio-eiffel-symbols.xml as a library. Have you seen that before?

**Comment by Fredrik10a** [comment]
I have not seen that before, I tested now to load on my private laptop from a clean DrawIO and it worked. 
I cannot say what that error might be =/

**Comment by magnusbaeck** [comment]
Okay, must've been a temporary glitch or something weird going on the machine where I tried it. Works fine for me now (on another machine). Thanks!

**Review by magnusbaeck — APPROVED** [review]

**Review by m-linner-ericsson — APPROVED** [review]

**Pull request merged**
